### ISSUE TITLE
User-Agent

### ISSUE THREAD

**Issue by VeNoMouS** [mskian/tor-python#2]
Hi @mskian,

I'm the author of cloudscraper, just spotted your project, go careful with manually setting `User-Agent` the way you have as Cloudflares BIC is very picky about header order, cloudscraper actually randomly picks a User-Agent for you from https://github.com/VeNoMouS/cloudscraper/blob/master/cloudscraper/user_agent/browsers.json, this sets up the header order correctly as well.. just figured id save you some hassle if you were getting reCaptcha  :) or 403 or failed challenge... if you want to use that specific User-Agent you have defined https://github.com/mskian/tor-python/blob/master/torurl.py#L12 , i would recommend you set the headers to OrderedDict and construct the rest of the headers according 

```
# User Agent
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.119 Safari/537.36'}

# Start Session
s = cloudscraper.create_scraper() # https://github.com/Anorov/cloudflare-scrape/issues/103
# Proxy Connection
s.proxies = proxies
# Bypass Cloudflare Enabled website - https://support.cloudflare.com/hc/en-us/articles/203306930-Does-Cloudflare-block-Tor-
scraper = cloudscraper.create_scraper(sess=s, delay=10)
.....
response = scraper.get(LINK, headers=headers)
```

```
scraper = cloudscraper.create_scraper()
scraper.proxies = {
    'http': 'socks5://127.0.0.1:9050',
    'https': 'socks5://127.0.0.1:9050'
}
....
response = scraper.get(LINK)
```

is all you would actually need..

**Comment by mskian** [comment]
Thanks for Reporting
let me check
Also Thanks for this Awesome Module :100:

**Comment by mskian** [comment]
Got this Error

```python
File "torurl.py", line 23, in <module>
    response = scraper.get(LINK)
  File "/home/groot/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/groot/.local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 146, in request
    if self.isChallengeRequest(resp):
  File "/home/groot/.local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 164, in isChallengeRequest
    raise ValueError('Captcha')
ValueError: Captcha
```

PS: Cloudflare Enabled website which ON the Onion option from crypto section are working well

**Comment by VeNoMouS** [comment]
Are you using the latest version of cloudscraper? 

```
import cloudscraper
cloudscraper.__version__
```

Also would you mind sharing the URL ?

**Comment by mskian** [comment]
Yes latest  `1.1.11`

**Comment by VeNoMouS** [comment]
Can i test the url myself?

**Comment by mskian** [comment]
Sure - `http://example.com`

**Comment by VeNoMouS** [comment]
```
>>> scraper = cloudscraper.create_scraper()
>>> scraper.get('http://example.com')
<Response [200]>
>>>
```

Hrmmm interesting...

For some Reasons, I update the URL to example.com

**Comment by mskian** [comment]
working on your side?

**Comment by mskian** [comment]
without TOR proxy its working

**Comment by VeNoMouS** [comment]
If you goto in your browser do you get a reCaptcha... (i assume your running the code on the same system)

**Comment by VeNoMouS** [comment]
Ah... but with Tor's breaking... yea that is mostly because of the proxy itself... if its setting up the TLS ciphers incorrectly ... and not doing SSL pass through.. CF's BIC is __EXTREMELY__ picky about the cipher's being offered.

**Comment by VeNoMouS** [comment]
Do you know if the proxy is doing SSL pass through or not? have you tried pushing a browser through the same proxy... does it encounter a reCaptcha?

**Comment by mskian** [comment]
Actually, Cloudflare giving an option to onion support in a crypto section if we enable it passes the TOR else we need to solve Captcha

**Comment by VeNoMouS** [comment]
Interesting.. do you have any information on that? if its not too hard i might be able to incorporate that i really need to add in 3rd party reCaptcha support too if i find some free time later next week I'll try add it in...

**Comment by mskian** [comment]
@VeNoMouS  check this - https://support.cloudflare.com/hc/en-us/articles/203306930-Does-Cloudflare-block-Tor-

**Comment by VeNoMouS** [comment]
I found ... https://blog.cloudflare.com/cloudflare-onion-service/

**Comment by mskian** [comment]
any solution?

**Comment by mskian** [comment]
Previously it's working

**Comment by VeNoMouS** [comment]
Can you show me your new code?

**Comment by mskian** [comment]
```python
# set the proxies.
proxies = {'http': 'socks5://127.0.0.1:9050',
           'https': 'socks5://127.0.0.1:9050'}

# Start Scraper
scraper = cloudscraper.create_scraper()
# Proxy Connection
scraper.proxies = proxies
response = scraper.get(LINK)
```

**Comment by VeNoMouS** [comment]
and it works if you use the old code?

**Comment by VeNoMouS** [comment]
@mskian i've emailed you a discord invite

**Comment by mskian** [comment]
Nope same issue I tested also downgrade the version same error for some site not enable the onion option

**Comment by VeNoMouS** [comment]
@mskian latest version 1.1.15 adds support for 3rd party reCaptcha solves... anti-captcha.com and deathbycaptcha.com

**Comment by mskian** [comment]
Got this error (Version 1.1.16 - Latest)

```python
RuntimeError: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.
```

This issue caused when using TOR proxy but without proxy, it's working fine

**Comment by VeNoMouS** [comment]
As I have tried to explaining to you, cloudflare knows alot of the TOR exit nodes.. i rarely get a node that CF is not aware of, it is not my code causing the reCaptcha... hence me putting in 3rd party reCaptcha solvers... that "error" as you put it... is stating that it detected a reCaptcha request but you haven't loaded a 3rd party reCaptcha to solve it...  https://github.com/VeNoMouS/cloudscraper#3rd-party-recaptcha-solvers

This was all explained to you on my discord....

**Comment by mskian** [comment]
Got it now :smiley:
